### ISSUE TITLE
Python packaging

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#1]
Currently all the work in this repo exists as a single file (`atlas_reader.py`). I think this will eventually become somewhat unwieldy as functionality is added/updated, so I'm planning to work on quickly converting everything into a more standard python package framework. I'll try to whip this up quickly so edits can be made&mdash;I'll open a PR soon!

**Comment by miykael** [comment]
Perfect @rmarkello - That's exactly what we need to start the project! Also, I'm new to packaging, so I'm happy if somebody does it with experience.
