### ISSUE TITLE
Have option to specify output directory

### ISSUE THREAD

**Issue by danjgale** [miykael/mni_atlas_reader#11]
Currently, output files save to the directory of the input stat map. An idea is to have this as the default, but also have the option to specify a new directory should if preferred.

**Comment by rmarkello** [comment]
I think this is a great idea!! Since I'm working on implementing `argparse` right now (to respond to #8), I'll assign myself to this and try to include it in the same PR.

**Comment by rmarkello** [comment]
Closed by #19
