### ISSUE TITLE
Leverage nilearn.datasets for atlases + templates

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#14]
Right now we're limiting the atlas + template options to the ones that are shipped with the repository (though see #4 for discussion of removing those), but we could also expand this to include any of the atlases / templates that are accessible via the [`nilearn.datasets`](http://nilearn.github.io/modules/reference.html#module-nilearn.datasets) package! If one of those atlases is requested (say, [`atlas_msdl`](http://nilearn.github.io/modules/generated/nilearn.datasets.fetch_atlas_msdl.html#nilearn.datasets.fetch_atlas_msdl)), then the appropriate `nilearn` fetch-style command could be called and the atlas downloaded + used.

I think this would be really worthwhile since `nilearn` is incredibly good about incorporating new atlases quickly after they're released. This may (at least temporarily) resolve the need for a separate repo in #4 (sorry, `corgi`)!

**Comment by miykael** [comment]
That's a great idea (even though I'm very sad about `corgi`).

As an additional pointer, I have a script that uses nilearn to quickly resample an atlas to a specific voxel resolution. It goes something as follows:

```python
from nibabel import load, Nifti1Image
from nilearn.image import resample_img
from nibabel.spaces import vox2out_vox

# Desired voxel resolution
res = [2, 2, 3]

# Load image
img = load('1.0mm_brain.nii.gz')

# Get output shape and affine
target_shape, target_affine = vox2out_vox(img, voxel_sizes=[res, res, res])

# Resample image
res_img = resample_img(img, target_affine, target_shape, clip=True)

# Save image in new resolution
res_img.to_filename('2.0mm_brain.nii.gz')
```

Not sure if this is useful for all atlases, but at least for some I think it's useful.
