### ISSUE TITLE
Thoughts on licensing?

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#2]
Is there any reason the license is GPL? I'm more a fan of MIT or BSD, especially for these sorts of projects that could very reasonably be incorporated into other projects! 

What are your thoughts about potentially changing it to something more permissive?

**Comment by rmarkello** [comment]
@miykael this is mostly your codebase so I think that this is ultimately something for you to decide on (hence why I'm both assigning to you _and_ pinging you).

I would be happy to see this moved to a BSD license as in [`mriqc`](https://github.com/poldracklab/mriqc) or [`fmriprep`](https://github.com/poldracklab/fmriprep/), but am happy to hear your thoughts.

**Comment by miykael** [comment]
@rmarkello completly fine with BSD (or MIT in this regard). I actually don't know the exact difference between all of them and just started to use one over the other. So, let's move it to BSD!

**Comment by miykael** [comment]
I did a benevolent dictator thing and changed the license to BSD. Please let me know if you're not ok with that and I'm happy to discuss it.

**Comment by rmarkello** [comment]
Sweet! That works for me so I'm closing this for now.

**Comment by KirstieJane** [comment]
🎉🎉🎉
Love it!!
🤗✨💖
