### ISSUE TITLE
Clean up output .csv file

### ISSUE THREAD

**Issue by danjgale** [miykael/mni_atlas_reader#22]
Hi all, 

Just tossing out a few ideas regarding the output file. Currently the output file contains both peak and cluster information, as shown below:

ClusterID | Peak_Location | Cluster_Mean | Volume | Harvard_Oxford
-- | -- | -- | -- | --
Cluster01 | 60.0_-19.0_46.0 | 7.2740965 | 27324 | 48.91% Postcentral_Gyrus
Cluster02 | -24.0_-31.0_73.0 | -7.2317147 | 11772 | 63.53% Postcentral_Gyrus; 36.24%   Precentral_Gyrus
Cluster03 | -9.0_-58.0_-17.0 | 6.786522 | 5049 | 88.77% No_label
Cluster04 | 51.0_-22.0_19.0 | 6.641388 | 4293 | 39.62% Parietal_Operculum_Cortex;   37.74% Central_Opercular_Cortex
Cluster05 | 24.0_-49.0_-26.0 | -6.504359 | 3618 | 88.06% No_label
Cluster06 | 6.0_-10.0_52.0 | 6.0106235 | 2646 | 63.27%   Juxtapositional_Lobule_Cortex_(formerly_Supplementary_Motor_Cortex)
Cluster07 | 33.0_-7.0_-2.0 | 6.2991576 | 378 | 85.71% Right_Putamen
PeakID | Peak_Location | Peak_Value | Volume | Harvard_Oxford
Peak01 | 60.0_-19.0_46.0 | 7.941345 | 27324 | 44% Postcentral_Gyrus
Peak02 | -24.0_-31.0_73.0 | -7.9414444 | 11772 | 47% Postcentral_Gyrus
Peak03 | -9.0_-58.0_-17.0 | 7.941345 | 5049 | 0% No_label
Peak04 | 51.0_-22.0_19.0 | 7.941345 | 4293 | 55% Parietal_Operculum_Cortex
Peak05 | 24.0_-49.0_-26.0 | -7.9414444 | 3618 | 0% No_label
Peak06 | 6.0_-10.0_52.0 | 7.941345 | 2646 | 53%   Juxtapositional_Lobule_Cortex_(formerly_Supplementary_Motor_Cortex)
Peak07 | 33.0_-7.0_-2.0 | 7.9053116 | 378 | 71% Right_Putamen

You'll notice a second header row with `PeakID`  is followed by the peak information rows. This makes it difficult to use with say, `pandas`, because now the column types will all be set as `object` and won't reflect the actual data type (e.g., `Cluster_Mean` should be `float`). 

So, my first suggestion is to break up these tables into a `peak.csv` and a `cluster.csv` with a way to link the peaks with their clusters across tables (i.e. using a column that matches a peak to its cluster). 

My second suggestion is to break coordinate information into separate x, y, and z columns (i.e. peak_x, peak_y, peak_z) so that these can fit cleanly in a table. 

Let me know what you guys think or what other improvements might be worthwhile. I'm happy to work on this.

**Comment by miykael** [comment]
@danjgale those are all good ideas. I'm all for that.
Creating two different files for peak and cluster, as well as separating the x, y z coordinates.
