### ISSUE TITLE
Demo notebook breaks on up-to-date version of nilearn

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#27]
The `fetch_neurovault_motor_task()` and `fetch_neurovault_auditory_computation_task()` functions no longer exist in `nilearn`. It would be great to update the demo notebook to reflect the newest fetch functions from `nilearn`, like `fetch_localizer_button_task()` and `fetch_localizer_calculation_task()`!

**Comment by rmarkello** [comment]
Ah, this _does_ work if you install the alpha release of `nilearn` (0.5.0a). It's just cutting edge! Closing for now.

**Comment by miykael** [comment]
Good to know!
Can't wait for nilearn 0.5.0, than I can finally incorporate the nice `view` functions in everything I do :-)
