### ISSUE TITLE
Hyphens or underscores in atlas names

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#28]
Currently the atlas files have mixed uses of hyphens (e.g., `desikan-killiany`) and underscores (e.g., `harvard_oxford`). I think we should likely settle on _either_ hyphens or underscores and rename all instances of the other to fit!

My preference is underscores, but I am happy to do whatever everyone thinks best!

**Comment by miykael** [comment]
Yes, I agree. Underscore is fine for me.
