### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#3]
I think it would be great to have a Code of Conduct (for so many reasons, including all those listed [here](http://bit.ly/NH18-OpenForAll-Slides)), especially given this is a collaborative project being actively developed at a [hackathon](http://neurohackademy.org/)! Contributor Convenant has a wonderful [template available here](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) that I use in [some of](https://www.github.com/rmarkello/pyls) [my projects](https://www.github.com/rmarkello/snfpy).

@miykael I think it would make sense, as the owner of the repo, for you to be the main person for handling reporting, but I am also happy to be listed for this.

Does anyone else who is interested in getting involved in the project have any thoughts on this?

**Comment by miykael** [comment]
That's an awesome idea! @rmarkello, I haven't done this before and really should introduce this to all my projects. As you have it already ready from your other projects, do you want to set it up for this as well?

Yes, set you up as handling reporting as well!
