### ISSUE TITLE
Docstrings needed

### ISSUE THREAD

**Issue by rmarkello** [miykael/mni_atlas_reader#7]
We need doc-strings! The current functions in `atlas_reader.py` have one-line descriptions of their functionality, if that. I am personally a fan of [`numpy`-style doc-strings](http://numpydoc.readthedocs.io/en/latest/format.html) since they interface so nicely with online documentation (like [Sphinx](http://www.sphinx-doc.org/en/master/)!).

It would be great if someone would be willing to go through the functions and document them with at least (1) a short description, (2) parameters + types, and (3) return values.

I talked to @danjgale about doing this, but if anyone else has thoughts on doc-strings this is the place to discuss!

**Comment by danjgale** [comment]
I did some work towards improving the documentation in [mni_atlas_reader/atlas_reader.py](https://github.com/miykael/mni_atlas_reader/blob/master/mni_atlas_reader/atlas_reader.py) in #13 which @miykael has merged in.

Now that @rmarkello has added some additional information in the `argparse` section, I'm going to keep improving the help for each function
