### ISSUE TITLE
Requirements.txt needed

### ISSUE THREAD

**Issue by danjgale** [miykael/mni_atlas_reader#9]
Currently missing a requirements.txt or environment.yml (if we go with conda)

**Comment by miykael** [comment]
@danjgale - That's very much needed. I'm not sure if it makes sense to go with requirements.txt instead of envrionment.yml. It might be too extreme to create a new conda environment (a few GBs), just for this toolbox.

But we could look into creating a [PyPI](https://pypi.org/) project?

**Comment by danjgale** [comment]
I think requirements.txt makes more sense than environment.yml because it can be used with either conda or pip

**Comment by miykael** [comment]
Yes, I'm also for `requirements.txt` file. Just asked @rmarkello  and he's agreeing.
@danjgale - do you want to set this up?
